### ISSUE TITLE
System requirements 

### ISSUE THREAD

**Issue by daniep01** [owaits/ScreenMonkey.Help#1]
@owaits please provide up to date system requirements and supported operating systems

**Comment by owaits** [comment]
Suggested minimum PC specification when playing video.

Intel i5 or Equivalent
GPU Score above 800
Dual Monitor Output
Windows 10
.Net Framework 4.5 or newer
FFDShow Installed (Ideally through k-lite codec pack)
Microsoft Office 2013 (when using Power Point clips)
