### ISSUE TITLE
Decklink renderer

### ISSUE THREAD

**Issue by daniep01** [owaits/ScreenMonkey.Help#4]
I assume this is gone and not coming back? I can't see it as an option.

**Comment by owaits** [comment]
It is still in the code and functional for custom rendered clip types but it does not work with video and having it in the software caused confusion around people expecting it to work with video. It does still have its uses and if I get the time to make it work with video I will probably re-introduce it.

**Comment by daniep01** [comment]
I’ll keep the decklink.md file and remove it from the toc
