### ISSUE TITLE
Does the user forum still exist

### ISSUE THREAD

**Issue by daniep01** [owaits/ScreenMonkey.Help#7]
I can’t seem to login any more - should I remove the link in the docs?

**Comment by owaits** [comment]
I do want to re-instate it but I had to disable it due to too much spam. I am looking at alternative options. If anyone has any ideas please let me know.

**Comment by daniep01** [comment]
I’ve added a link to the facebook group

**Comment by owaits** [comment]
Great, I think that is probably best for the moment.
