### ISSUE TITLE
How does link edit mode work?

### ISSUE THREAD

**Issue by daniep01** [owaits/ScreenMonkey.Help#9]
I can see that in link edit mode right clicking on a clip opens the link browser. What else? The old help doc is quite unclear.

**Comment by owaits** [comment]
The basic principal is that you select a clip you want to link from using the left mouse button and it should become selected. Any clips already linked will be shown with a green border and a legend of what type of link exists from the selected clip. If you want to add links to a clip from the selected clip then left click and it will open the link editor with the target clip already selected. Enter the link information and then when you click OK a link will be added from the selected clip to the one you right clicked on.
